translate
atom-china/manual pull request #40
Opened 2017-12-27 05:19 UTC by 1977744311

翻译完成，因为是第一次参加如有错误请指出。

2017-12-27 14:03 UTC, mzlogin requested changes

2017-12-27 14:03 UTC, mzlogin commented on chapter-5-upgrading-to-1.0-APIs/upgrading-your-syntax-theme.md
> +文本编辑器的内容现在支持在 shadow DOM 中，这样可以有效的避免某些样式被全局样式表所影响，用来防止意外出现的样式污染。有关 shadow DOM 的更多背景信息，请查看 HTML 5 Rocks 上的 [shadow DOM 101](https://www.html5rocks.com/en/tutorials/webcomponents/shadowdom/) 。
render 译为渲染更合适。

以下译法供参考：

`文本编辑器里的内容是在 shadow DOM 中渲染，shadow DOM 用于保护内容的样式不被全局样式表所污染。`

2017-12-27 14:03 UTC, mzlogin commented on chapter-5-upgrading-to-1.0-APIs/upgrading-your-syntax-theme.md
> +语法主题是专门用于设置文本编辑器内容的样式，因此在启用文本编辑器的 shadow DOM 时，它们会自动直接加载到文本编辑器的 shadow DOM 中。当主题的 `package.json` 包含 `theme:"syntax"` 描述语句时将会自动运行，因此你不需要改变任何内容来适应你目标的上下文。
declaration 译为声明可能更准确。

“自动运行”可以换个更贴切的说法。

这类翻译中”你”一般可以省掉。

2017-12-27 14:03 UTC, mzlogin commented on chapter-5-upgrading-to-1.0-APIs/upgrading-your-syntax-theme.md
> +当主题样式表加载到文本编辑器的 shadow DOM 中时，想要从外部对准编辑器的选择器将不再有意义。以 `.editor` 和 `.editor-color` 类为目标的样式需要定位到 `:host` 伪元素，该伪元素与包含的 `atom-text-editor` 节点相匹配。有关 `:host` 伪元素的更多信息，请参阅 [shadow DOM 201](https://www.html5r
“对准”这个译法有点奇怪……

 no longer make sense 也许可以译为“不起作用”

“定位到”改为“以...为目标”也许更好

2017-12-27 14:03 UTC, mzlogin commented on chapter-5-upgrading-to-1.0-APIs/upgrading-your-syntax-theme.md
> +这里有一个来自 Atom 的 light 语法主题的例子。请注意，从外部对准编辑器的 `atom-text-editor` 选择器已被保留下来，当禁用 shadow DOM 的时候用来允许主题在过渡阶段保持工作状态。
“对准”可以再想想更合适的译法

2017-12-27 14:49 UTC, 1977744311 commented
修改完成，请查看

2018-01-11 12:11 UTC, mzlogin approved these changes

2018-01-11 12:12 UTC, merged

2018-01-11 12:13 UTC, mzlogin commented
Merged, thx!